name: socket_io_client
description: Dartlang port of socket.io-client
version: 0.8.2
author: jumperchen <jumperchen@potix.com>
homepage: https://www.zkoss.org

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  logging: ^0.11.3+2
  socket_io: any

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  
